import { countries, lifeAreas, cities, services, stories } from './data.js';

const app = document.querySelector('#app');
const link = (path, label, className = '') => `<a class="${className}" href="${path}">${label}</a>`;
const pageHero = (eyebrow, title, text) => `<section class="page-hero"><div class="container"><div class="breadcrumb">${eyebrow}</div><h1>${title}</h1><p>${text}</p></div></section>`;

function header() {
  return `<header class="site-header"><a class="wordmark" href="/">BRAZILIANS.ME<span>BRASILEIROS VIVENDO O MUNDO.</span></a><nav class="nav" id="main-nav">${link('/', 'Explorar')}${link('/portugal', 'Países')}${link('/familia', 'Família')}${link('/familia', 'Vida fora')}${link('/servicos', 'Serviços')}${link('/historias', 'Histórias')}${link('/comunidade', 'Comunidade')}<a class="nav-cta" href="/participar">Quero participar</a></nav><button class="menu-toggle" id="menu-toggle" aria-label="Abrir menu">☰</button></header>`;
}

function footer() {
  return `<footer class="footer container"><div><a class="wordmark" href="/">BRAZILIANS.ME<span>Brasileiros vivendo o mundo.</span></a><p style="margin:18px 0 0">Protótipo demonstrativo · 2026</p></div><div class="footer-links">${link('/', 'Sobre')}${link('/', 'Como funciona')}${link('/portugal', 'Países')}${link('/servicos', 'Serviços')}${link('/historias', 'Histórias')}${link('/comunidade', 'Comunidade')}${link('/participar', 'Contato')}</div></footer>`;
}

function mapSvg() {
  const mapCountries = [
    ['Estados Unidos', 'estados-unidos', 'M 105 125 L 137 102 L 184 110 L 203 135 L 178 155 L 140 153 L 118 172 L 91 150 Z', 141, 138],
    ['Portugal', 'portugal', 'M 462 175 L 475 167 L 481 181 L 470 191 L 458 185 Z', 471, 180],
    ['Espanha', 'espanha', 'M 475 154 L 528 151 L 544 174 L 507 190 L 474 181 Z', 508, 169],
    ['Irlanda', 'irlanda', 'M 530 86 L 546 78 L 558 91 L 546 106 L 530 101 Z', 544, 92],
    ['Japão', 'japao', 'M 766 158 L 780 143 L 793 158 L 784 180 L 771 191 Z', 785, 165],
    ['Brasil', 'brasil', 'M 255 195 L 302 182 L 347 202 L 366 245 L 347 295 L 311 323 L 274 292 L 250 248 Z', 309, 252]
  ];
  return `<svg class="map" viewBox="0 0 900 370" role="img" aria-label="Mapa demonstrativo com países navegáveis"><path class="map-land" d="M70 80 L180 58 L250 84 L315 68 L385 88 L438 62 L532 44 L640 72 L714 56 L828 103 L864 173 L824 216 L859 260 L780 311 L674 290 L615 327 L519 298 L449 318 L382 285 L321 341 L235 315 L184 269 L102 278 L58 220 Z"/><g>${mapCountries.map(([name, slug, path, x, y]) => `<a href="/${slug}" data-country="${slug}" aria-label="Explorar ${name}"><path class="map-land" d="${path}"/><circle class="map-dot" cx="${x}" cy="${y}" r="5"/><text class="map-label" x="${x + 9}" y="${y + 4}">${name}</text></a>`).join('')}</g></svg>`;
}

function mapSection() {
  return `<section class="section" id="mapa"><div class="container"><div class="section-head"><div><div class="eyebrow">Comece por onde você está</div><h2>Um mundo de histórias brasileiras.</h2></div><p>Selecione um país para descobrir comunidades, cidades, vida cotidiana e novas conexões. <span class="demo-tag">DADO DE DEMONSTRAÇÃO</span></p></div><div class="map-shell">${mapSvg()}<div class="map-tooltip"><span class="flag">🇵🇹</span><h3>Portugal</h3><p>Explore comunidades, cidades, vida cotidiana, serviços e histórias.</p>${link('/portugal', 'Explorar Portugal', 'button')}</div></div></div></section>`;
}

function countryCards() {
  return `<div class="country-grid">${countries.map(country => `<a class="country-card ${country.featured ? 'featured' : ''}" href="/${country.slug}"><span class="flag">${country.flag}</span><h3>${country.name}</h3><p><strong>${country.city}</strong><br>${country.people}</p><span class="text-link">Explorar ${country.name} →</span></a>`).join('')}</div>`;
}

function home() {
  const stages = [['ANTES DE IR', 'Planejamento, documentação, orçamento e preparação da família.'], ['CHEGANDO', 'Os primeiros dias, moradia, escola, transporte, serviços e adaptação.'], ['VIVENDO FORA', 'Trabalho, família, saúde, dinheiro, amizades, cultura e pertencimento.'], ['CRIANDO FILHOS FORA', 'Educação, bilinguismo, identidade cultural e desenvolvimento.'], ['MANTENDO VÍNCULOS', 'Família no Brasil, viagens, tecnologia e relações à distância.'], ['PENSANDO EM VOLTAR', 'Retorno, carreira, escola, patrimônio e recomeço.']];
  return `${header()}<main><section class="hero"><div class="container hero-grid"><div><div class="eyebrow">Um portal 360° para brasileiros no exterior</div><h1>Brasileiros <em>vivendo</em> o mundo.</h1><p class="lede">Informação, comunidade e conexões para brasileiros e suas famílias onde quer que estejam.</p><div class="actions">${link('#mapa', 'Explorar o mundo', 'button')}${link('/comunidade', 'Encontrar brasileiros', 'button secondary')}</div></div><div class="hero-note"><strong>País → Cidade → Comunidade → Vida</strong>Uma nova forma de encontrar informação, pessoas e pertencimento fora do Brasil.</div></div></section>${mapSection()}<section class="section lined"><div class="container"><div class="section-head"><div><div class="eyebrow">A vida não cabe em uma categoria</div><h2>Um mundo, muitas vidas.</h2></div><p>Viver fora do Brasil não é apenas mudar de país. Cada pessoa vive uma experiência diferente.</p></div><div class="area-grid">${lifeAreas.map(([icon, title]) => `<div class="area"><span class="area-icon">${icon}</span><h3>${title}</h3></div>`).join('')}</div></div></section><section class="section lined"><div class="container"><div class="section-head"><div><div class="eyebrow">Explore por país</div><h2>Comece a construir seu mapa.</h2></div><p>Conteúdo editorial, comunidade e serviços em um só lugar.</p></div>${countryCards()}</div></section><section class="section lined"><div class="container"><div class="section-head"><div><div class="eyebrow">A vida fora do Brasil</div><h2>Para cada momento da jornada.</h2></div></div><div class="life-grid">${stages.map(([stage, text]) => `<article class="life-card"><div class="stage">${stage}</div><h3>${stage === 'VIVENDO FORA' ? 'Sua vida acontece aqui.' : stage[0] + stage.slice(1).toLowerCase() + '.'}</h3><p>${text}</p></article>`).join('')}</div></div></section><section class="container cta-band"><div class="eyebrow" style="color:#ffe8df">Uma construção coletiva</div><h2>Você vive fora do Brasil?</h2><p>Estamos construindo o BRAZILIANS.ME para brasileiros que vivem o mundo todos os dias.</p>${link('/participar', 'Quero participar', 'button')}</section></main>${footer()}`;
}

function portugal() {
  return `${header()}<main>${pageHero('🇵🇹 Portugal · País', 'Brasileiros vivendo em Portugal', 'Descubra cidades, comunidades, experiências e informações para brasileiros vivendo em Portugal.')}<section class="section"><div class="container"><div class="section-head"><div><div class="eyebrow">Cinco pontos de partida</div><h2>Cidades para chamar de próximo capítulo.</h2></div><span class="demo-tag">CONTEÚDO DE PROTÓTIPO</span></div><div class="city-grid">${cities.map(([name, text, slug]) => `<a class="city-card" href="${slug === 'lisboa' ? '/portugal/lisboa' : '/portugal'}"><span class="eyebrow">🇵🇹 Portugal</span><h3>${name}</h3><p>${text}</p><span class="text-link">Explorar ${name} →</span></a>`).join('')}</div></div></section><section class="section lined"><div class="container split"><div><div class="eyebrow">Uma visão mais ampla</div><h2>A vida acontece em muitas camadas.</h2><p class="lede">Da primeira busca por moradia às relações que ficam para sempre, Portugal é o cenário. A vida de cada brasileiro é a história.</p></div><div class="panel"><span class="demo-tag">DADO DE DEMONSTRAÇÃO</span><h3 style="font-size:23px;margin:22px 0 10px">O que você quer descobrir?</h3><p style="color:var(--ink-soft)">Comunidade, família, carreira, educação, saúde, cultura e conexões podem começar aqui.</p>${link('/portugal/lisboa', 'Entrar em Lisboa', 'button')}</div></div></section></main>${footer()}`;
}

function lisboa() {
  const blocks = [['◉', 'COMUNIDADE', 'Quem são os brasileiros que vivem aqui?'], ['⌂', 'VIDA PRÁTICA', 'Moradia, transporte, documentação, escolas e serviços.'], ['♧', 'FAMÍLIA', 'Vida familiar, crianças, adolescentes e relacionamentos.'], ['↗', 'TRABALHO', 'Emprego, empreendedorismo e carreira.'], ['⌘', 'EDUCAÇÃO', 'Escolas, universidades, idiomas e educação brasileira.'], ['✦', 'SAÚDE E BEM-ESTAR', 'Saúde física, mental e emocional.'], ['♫', 'CULTURA', 'Eventos, música, gastronomia e identidade brasileira.'], ['◎', 'CONEXÕES', 'Profissionais, negócios e brasileiros da comunidade.']];
  return `${header()}<main>${pageHero('🇵🇹 Portugal / Lisboa', 'Brasileiros vivendo em Lisboa', 'Uma visão da comunidade, da vida cotidiana e das conexões disponíveis na cidade.')}<section class="section"><div class="container split"><div><div class="eyebrow">A cidade como ponto de encontro</div><h2>Lisboa, vista por quem vive o mundo.</h2><p class="lede">Uma página demonstrativa para organizar tudo o que importa quando uma cidade passa a fazer parte da sua história.</p></div><div class="panel"><span class="demo-tag">RETRATO DEMONSTRATIVO</span><div class="stats" style="margin-top:22px"><div class="stat"><small>População brasileira</small><strong>Dado demonstrativo</strong></div><div class="stat"><small>Famílias</small><strong>Dado demonstrativo</strong></div><div class="stat"><small>Profissionais cadastrados</small><strong>Dado demonstrativo</strong></div><div class="stat"><small>Eventos</small><strong>Dado demonstrativo</strong></div></div><p style="font-size:11px;color:var(--ink-soft);margin:16px 0 0">Os números acima são ilustrativos e serão substituídos por dados verificáveis na versão pública.</p></div></div></section><section class="section lined"><div class="container"><div class="section-head"><div><div class="eyebrow">Uma cidade, muitas dimensões</div><h2>Encontre a parte da vida que você quer viver.</h2></div><span class="demo-tag">CONTEÚDO DE PROTÓTIPO</span></div><div class="feature-grid">${blocks.map(([icon, title, text]) => `<article class="feature-card"><span class="area-icon">${icon}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></div></section><section class="section lined"><div class="container"><div class="section-head"><div><div class="eyebrow">Pessoas e serviços</div><h2>Conexões que fazem a cidade ficar menor.</h2></div>${link('/servicos', 'Ver serviços', 'button secondary')}</div><div class="profile"><div class="avatar">K</div><div><span class="demo-tag">PERFIL DEMONSTRATIVO DO PROTÓTIPO</span><h2>Kelly Ilkyo</h2><p>Psicóloga · Atendimento online · Brasileiros vivendo no exterior · Português<br>Brasil / atendimento remoto</p>${link('/servicos', 'Conhecer a proposta', 'button')}</div></div></div></section></main>${footer()}`;
}

function contentPage(type) {
  const config = { familia: ['Família 360°', 'Porque morar fora muda a vida de toda a família.', [['👫','Casais'],['👶','Crianças'],['🧑‍🎓','Adolescentes'],['👴','Avós e familiares no Brasil'],['🏠','Rotina familiar'],['❤️','Relacionamentos'],['🗣️','Bilinguismo'],['🧠','Saúde emocional'],['🎓','Educação'],['✈️','Visitas ao Brasil']]], plh: ['Português como Língua de Herança', 'Manter o português vivo quando a família vive fora do Brasil.', [['Aa','Como manter o português em casa'],['▣','Livros brasileiros'],['♫','Música brasileira'],['◡','Brincadeiras'],['⌘','Escolas e professores'],['◉','Comunidades brasileiras'],['↔','Bilinguismo'],['◒','Cultura e identidade']]], trabalho: ['Trabalho e carreira', 'Reconstruir caminhos profissionais também faz parte de viver o mundo.', [['💼','Emprego'],['🚀','Empreendedorismo'],['🌎','Trabalho remoto'],['🎓','Requalificação'],['🗣️','Idiomas'],['💻','Profissões digitais'],['👩‍💼','Carreira do cônjuge'],['🔄','Reconhecimento profissional']]], saude: ['Saúde e bem-estar', 'Informação acolhedora para cuidar de si e da família fora do Brasil.', [['🧠','Saúde mental'],['🩺','Saúde física'],['👨‍👩‍👧','Saúde da família'],['👶','Desenvolvimento infantil'],['❤️','Relacionamentos'],['🧓','Envelhecimento'],['🌎','Adaptação cultural']]] }[type];
  return `${header()}<main>${pageHero('BRAZILIANS.ME · Vida fora', config[0], config[1])}<section class="section"><div class="container"><div class="topic-grid">${config[2].map(([icon, title]) => `<article class="topic"><span>${icon}</span>${title}</article>`).join('')}</div></div></section>${type === 'familia' || type === 'plh' ? `<section class="section lined"><div class="container split"><div><div class="eyebrow">Uma conversa importante</div><h2>${type === 'plh' ? 'Quando a língua encontra a casa.' : 'Quando uma criança brasileira cresce fora do Brasil.'}</h2><p class="lede">${type === 'plh' ? 'Português, livros, música e memória podem encontrar espaço na rotina sem transformar a família em uma sala de aula.' : 'Português como língua de herança, bilinguismo, identidade, escola, amizades, pertencimento e relação com os avós fazem parte dessa experiência.'}</p></div><article class="panel"><span class="demo-tag">EXEMPLO ILUSTRATIVO</span><h3 style="font-family:Fraunces;font-size:28px;margin:22px 0 10px">${type === 'plh' ? 'Pequenos rituais, grandes vínculos.' : 'Meu filho entende português, mas responde em inglês. Isso é normal?'}</h3><p style="color:var(--ink-soft)">Uma pauta demonstrativa para abrir conversas. O protótipo não oferece diagnóstico nem afirmações clínicas.</p></article></div></section>` : `<section class="section lined"><div class="container panel"><span class="demo-tag">DESTAQUE DEMONSTRATIVO</span><h2 style="font-size:42px;margin:20px 0 12px">${type === 'trabalho' ? 'Quando a mudança de país interrompe uma carreira' : 'Cuidar também é encontrar contexto.'}</h2><p class="lede">${type === 'trabalho' ? 'Uma mudança pode pedir outras palavras para contar o que você já sabe fazer. Esta página abre espaço para histórias de requalificação, empreendedorismo e carreira do cônjuge.' : 'Conteúdo de orientação e descoberta. O BRAZILIANS.ME não faz promessas médicas e não substitui profissionais habilitados.'}</p></div></section>`}</main>${footer()}`;
}

function servicesPage() {
  return `${header()}<main>${pageHero('BRAZILIANS.ME · Conexões', 'Encontre profissionais que entendem a vida brasileira fora do Brasil.', 'Um diretório demonstrativo para aproximar pessoas, serviços e contextos.')}<section class="section"><div class="container"><div class="service-grid">${services.map(([icon, title, text]) => `<article class="service-card"><span class="area-icon">${icon}</span><h3>${title}</h3><p>${text}</p><span class="demo-tag" style="margin-top:16px">PERFIL DEMONSTRATIVO</span></article>`).join('')}</div></div></section><section class="section lined"><div class="container"><div class="profile"><div class="avatar">K</div><div><span class="demo-tag">PERFIL DEMONSTRATIVO DO PROTÓTIPO</span><h2>Kelly Ilkyo</h2><p>Psicóloga · Atendimento online · Público: brasileiros vivendo no exterior · Foco demonstrativo: mulheres brasileiras vivendo fora do Brasil · Português · Brasil / atendimento remoto</p><p style="font-size:13px">Este perfil é utilizado nesta demonstração para ilustrar como profissionais brasileiros poderão apresentar seus serviços no BRAZILIANS.ME.</p></div></div></div></section></main>${footer()}`;
}

function storiesPage() { return `${header()}<main>${pageHero('BRAZILIANS.ME · Vozes', 'Histórias de quem vive o mundo', 'Relatos demonstrativos sobre mudança, identidade, família e recomeços.') }<section class="section"><div class="container story-grid">${stories.map(([number, title, text]) => `<article class="story"><span class="story-number">${number}</span><span class="demo-tag" style="float:right">HISTÓRIA DEMONSTRATIVA</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section></main>${footer()}`; }

function communityPage() { const questions = ['Como vocês mantêm o português das crianças?', 'Alguém conhece uma escola brasileira em Lisboa?', 'Como vocês mantêm contato com os avós?', 'Brasileiros em Dublin: como foi o primeiro inverno?']; return `${header()}<main>${pageHero('BRAZILIANS.ME · Comunidade', 'Uma comunidade de brasileiros espalhados pelo mundo.', 'Uma prévia de como pessoas, perguntas e experiências poderão se encontrar.') }<section class="section"><div class="container country-grid">${['Lisboa','Orlando','Dublin','Tóquio','Madrid'].map((city, i) => `<article class="country-card"><span class="flag">${['🇵🇹','🇺🇸','🇮🇪','🇯🇵','🇪🇸'][i]}</span><h3>Brasileiros em ${city}</h3><span class="demo-tag" style="margin-top:auto">CONTEÚDO DE DEMONSTRAÇÃO</span></article>`).join('')}</div></section><section class="section lined"><div class="container"><div class="section-head"><div><div class="eyebrow">Perguntas da comunidade</div><h2>Começar uma conversa.</h2></div></div><div class="story-grid">${questions.map(question => `<article class="story"><span class="demo-tag">CONTEÚDO DE DEMONSTRAÇÃO</span><h3>${question}</h3></article>`).join('')}</div></div></section></main>${footer()}`; }

function toolsPage() { const tools = [['🗺️','Encontrar consulados'],['💰','Custo de vida'],['📋','Checklist de mudança'],['💱','Conversor de moedas'],['🏫','Encontrar escolas'],['🧑‍⚕️','Encontrar profissionais'],['📍','Encontrar brasileiros']]; return `${header()}<main>${pageHero('BRAZILIANS.ME · Ferramentas', 'Pequenas ferramentas para uma vida grande.', 'Interfaces demonstrativas para organizar decisões, perguntas e próximos passos.') }<section class="section"><div class="container topic-grid">${tools.map(([icon, title]) => `<article class="topic"><span>${icon}</span>${title}<small style="display:block;color:var(--coral);font-size:10px;margin-top:10px">EM BREVE · DEMO</small></article>`).join('')}</div></section></main>${footer()}`; }

function participatePage() { return `${header()}<main>${pageHero('BRAZILIANS.ME · Participação', 'Você faz parte dessa comunidade?', 'Estamos construindo o BRAZILIANS.ME para brasileiros que vivem o mundo todos os dias.') }<section class="section"><div class="container form-shell"><span class="demo-tag">FORMULÁRIO DEMONSTRATIVO</span><h2 style="font-size:42px;margin:20px 0 25px">Compartilhe um pouco da sua experiência.</h2><form class="form-grid" id="participate-form"><div><label for="name">Nome</label><input id="name" required placeholder="Como podemos chamar você?" /></div><div><label for="country">País</label><input id="country" required placeholder="Onde você vive hoje?" /></div><div class="field-wide"><label for="city">Cidade</label><input id="city" placeholder="E a sua cidade?" /></div><div class="field-wide"><label for="difficulty">Qual é a maior dificuldade de viver fora do Brasil para você?</label><textarea id="difficulty"></textarea></div><div class="field-wide"><label for="wish">Que informação você gostaria de encontrar aqui?</label><textarea id="wish"></textarea></div><div class="field-wide"><button class="button" type="submit">Enviar contribuição</button><p id="form-message" style="color:var(--coral);font-size:13px;margin:14px 0 0"></p></div></form></div></section></main>${footer()}`; }

function simpleCountry(slug) { const country = countries.find(item => item.slug === slug) || countries[1]; return `${header()}<main>${pageHero(`${country.flag} País · Conteúdo demonstrativo`, `Brasileiros vivendo em ${country.name}`, `Uma página inicial para descobrir cidades, interesses e conexões de brasileiros vivendo em ${country.name}.`)}<section class="section"><div class="container split"><div><div class="eyebrow">Comece por uma cidade</div><h2>${country.city} é o ponto de partida.</h2><p class="lede">${country.description}</p></div><div class="panel"><span class="demo-tag">CONTEÚDO DE PROTÓTIPO</span><h3 style="font-size:23px;margin:22px 0 10px">Áreas de interesse</h3><p style="color:var(--ink-soft)">${country.people}. Comunidade, família, trabalho, educação, saúde, cultura e serviços.</p></div></div></section></main>${footer()}`; }

function render() {
  const path = window.location.pathname.replace(/\/$/, '') || '/';
  const pages = { '/': home, '/portugal': portugal, '/portugal/lisboa': lisboa, '/familia': () => contentPage('familia'), '/plh': () => contentPage('plh'), '/trabalho': () => contentPage('trabalho'), '/saude': () => contentPage('saude'), '/servicos': servicesPage, '/historias': storiesPage, '/comunidade': communityPage, '/ferramentas': toolsPage, '/participar': participatePage };
  const country = countries.find(item => `/${item.slug}` === path);
  app.innerHTML = pages[path] ? pages[path]() : country ? simpleCountry(country.slug) : `${header()}<main class="container empty-route"><div class="eyebrow">Página não encontrada</div><h1>Vamos voltar ao mapa.</h1>${link('/', 'Explorar o mundo', 'button')}</main>${footer()}`;
  window.scrollTo(0, 0);
  document.querySelector('#menu-toggle')?.addEventListener('click', () => document.querySelector('#main-nav')?.classList.toggle('open'));
  document.querySelector('#participate-form')?.addEventListener('submit', event => { event.preventDefault(); document.querySelector('#form-message').textContent = 'Obrigado. Esta contribuição é apenas uma simulação do protótipo.'; event.target.reset(); });
}

document.addEventListener('click', event => { const anchor = event.target.closest('a'); if (!anchor || !anchor.href.startsWith(window.location.origin) || anchor.target === '_blank') return; event.preventDefault(); const samePage = anchor.pathname === window.location.pathname && anchor.hash; history.pushState({}, '', anchor.pathname + anchor.hash); render(); if (samePage) document.querySelector(anchor.hash)?.scrollIntoView({ behavior: 'smooth' }); });
window.addEventListener('popstate', render);
render();